### PR TITLE
Shuffle code Update

### PR DESCRIPTION
**Pull request by vipansh**
Optimizations made:

1. Used the Fisher-Yates shuffle algorithm, which is more efficient.
2. Removed the unnecessary assignment inside the loop (`if (j !== i)` check), as the Fisher-Yates algorithm doesn't require it.
3. Used array slicing (`array.slice()`) to create a copy of the input array instead of modifying it directly.
4. Used array destructuring assignment for swapping elements, which is more concise and efficient.

### CODE REVIEW

**Comment by dcousens** [comment]
Thanks for the pull request! :blue_heart: 

> Used the Fisher-Yates shuffle algorithm, which is more efficient.

Can you verify this claim? What percentage improvement are we looking at? 

> Used array slicing (array.slice()) to create a copy of the input array instead of modifying it directly.

We didn't modify the input array previously

> Used array destructuring assignment for swapping elements, which is more concise and efficient.

Yes, but that eliminates some compatibility - I haven't checked what this syntax will set as the minimum versions

**Comment by vipansh** [comment]
# Can you verify this claim? What percentage improvement are we looking at?

I can't say in terms of percentage but let me try to explain it
### Original Logic:

For each loop iteration `(from i = 0 to i = n - 1)`, a random number is generated using `rng()`. So, there are `n` random calls.

### Fisher-Yates Shuffle Algorithm:

1. For each iteration of the loop `(from i = n - 1 to i = 1)`, a random number is generated using `rng()`. So, there are `n - 1` random calls.
2. remove conditionally swapping  If `j !== i`, resulting in less operations.

-----------------------------------------------------------------------------------

# We didn't modify the input array previously

You're correct. This point was to highlight my approach that a copy of the array was created within the function, and all modifications were applied to this copy



-----------------------------------------------------------------------------------

# Yes, but that eliminates some compatibility - I haven't checked what this syntax will set as the minimum versions

Array destructuring assignment was introduced in ECMAScript 2015 (ES6). Most modern browsers and Node.js versions support ES6 features, but if you want I can use a traditional approach to swap elements
```
let temp = result[i];
result[i] = result[j];
result[j] = temp;
```

**Comment by dcousens** [comment]
> I can't say in terms of percentage but let me try to explain it

Honestly, without the actual percentage benchmarks across a number of browsers, I can't approve this pull request as is.
Changes to the algorithmic complexity isn't always as straightforward as "less iterations is better".

**Comment by vipansh** [comment]
Hey again,

you can check https://jsbm.dev/ZH6KW5csFkWd5

I tried to check the average run time for both logic, but it may vary across different machines depending on their capabilities. Please feel free to check on your machine.

image

**Comment by dcousens** [comment]
Hi @vipansh,

10 million is an unlikely usecase for many users, [so I used an `N` value of `1000`.](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJNVVk2LUU2SXdwSGdPbXNDcDVBa0MiLCJjb2RlIjoiREFUQS5vbGRTaHVmZmxlKERBVEEuYXJyKSIsIm5hbWUiOiJPbGQgU2h1ZmZsZSAxMDAwIHZhbHVlcyIsImRlcGVuZGVuY2llcyI6W119LHsiaWQiOiJuOUtsLWJ3RGFZUlEtQm1XeGVJXzgiLCJjb2RlIjoiREFUQS5uZXdTaHVmZmxlKERBVEEuYXJyKSIsIm5hbWUiOiJOZXcgU2h1ZmZsZSAxMDAwIHZhbHVlcyIsImRlcGVuZGVuY2llcyI6W119XSwiY29uZmlnIjp7Im5hbWUiOiJCYXNpYyBleGFtcGxlIiwicGFyYWxsZWwiOnRydWUsImdsb2JhbFRlc3RDb25maWciOnsiZGVwZW5kZW5jaWVzIjpbXX0sImRhdGFDb2RlIjoiZnVuY3Rpb24gb2xkU2h1ZmZsZShhcnJheSwgcm5nKSB7XG4gIHJuZyA9IHJuZyB8fCBNYXRoLnJhbmRvbTtcbiAgY29uc3QgcmVzdWx0ID0gW107XG4gIGZvciAobGV0IGkgPSAwOyBpIDwgYXJyYXkubGVuZ3RoOyArK2kpIHtcbiAgICBjb25zdCBqID0gTWF0aC5mbG9vcihybmcoKSAqIChpICsgMSkpO1xuICAgIGlmIChqICE9PSBpKSB7XG4gICAgICByZXN1bHRbaV0gPSByZXN1bHRbal07XG4gICAgfVxuICAgIHJlc3VsdFtqXSA9IGFycmF5W2ldO1xuICB9XG4gIHJldHVybiByZXN1bHQ7XG59XG5cbmZ1bmN0aW9uIG5ld1NodWZmbGUoYXJyYXksIHJuZyA9IE1hdGgucmFuZG9tKSB7XG4gIGNvbnN0IHJlc3VsdCA9IGFycmF5LnNsaWNlKCk7IC8vIENyZWF0ZSBhIGNvcHkgb2YgdGhlIGFycmF5IHRvIGF2b2lkIG1vZGlmeWluZyB0aGUgb3JpZ2luYWxcbiAgZm9yIChsZXQgaSA9IHJlc3VsdC5sZW5ndGggLSAxOyBpID4gMDsgaS0tKSB7XG4gICAgY29uc3QgaiA9IE1hdGguZmxvb3Iocm5nKCkgKiAoaSArIDEpKTsgLy8gR2VuZXJhdGUgcmFuZG9tIGluZGV4IGZyb20gMCB0byBpIGluY2x1c2l2ZVxuICAgIFtyZXN1bHRbaV0sIHJlc3VsdFtqXV0gPSBbcmVzdWx0W2pdLCByZXN1bHRbaV1dOyAvLyBTd2FwIGVsZW1lbnRzIGVmZmljaWVudGx5XG4gIH1cbiAgcmV0dXJuIHJlc3VsdDtcbn1cblxuY29uc3QgTiA9IDEwMDBcbmNvbnN0IGFyciA9IEFycmF5LmZyb20oe2xlbmd0aDogTn0pLm1hcCgoXywgaSkgPT4gaSlcblxucmV0dXJuIHtcbiAgbmV3U2h1ZmZsZSxcbiAgb2xkU2h1ZmZsZSxcbiAgYXJyXG59OyJ9fQ)

2024-04-02T02_35_08

**Comment by vipansh** [comment]
IMG_20240402_185113
for 1000 also new logic is fast
check average run time


[link to test](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJNVVk2LUU2SXdwSGdPbXNDcDVBa0MiLCJjb2RlIjoiREFUQS5vbGRTaHVmZmxlKERBVEEuYXJyKSIsIm5hbWUiOiJPbGQgU2h1ZmZsZSAxME0gdmFsdWVzIiwiZGVwZW5kZW5jaWVzIjpbXX0seyJpZCI6Im45S2wtYndEYVlSUS1CbVd4ZUlfOCIsImNvZGUiOiJEQVRBLm5ld1NodWZmbGUoREFUQS5hcnIpIiwibmFtZSI6Ik5ldyBTaHVmZmxlIDEwTSB2YWx1ZXMiLCJkZXBlbmRlbmNpZXMiOltdfV0sImNvbmZpZyI6eyJuYW1lIjoiQmFzaWMgZXhhbXBsZSIsInBhcmFsbGVsIjp0cnVlLCJnbG9iYWxUZXN0Q29uZmlnIjp7ImRlcGVuZGVuY2llcyI6W119LCJkYXRhQ29kZSI6ImZ1bmN0aW9uIG9sZFNodWZmbGUoYXJyYXksIHJuZykge1xuICBybmcgPSBybmcgfHwgTWF0aC5yYW5kb207XG4gIGNvbnN0IHJlc3VsdCA9IFtdO1xuICBmb3IgKGxldCBpID0gMDsgaSA8IGFycmF5Lmxlbmd0aDsgKytpKSB7XG4gICAgY29uc3QgaiA9IE1hdGguZmxvb3Iocm5nKCkgKiAoaSArIDEpKTtcbiAgICBpZiAoaiAhPT0gaSkge1xuICAgICAgcmVzdWx0W2ldID0gcmVzdWx0W2pdO1xuICAgIH1cbiAgICByZXN1bHRbal0gPSBhcnJheVtpXTtcbiAgfVxuICByZXR1cm4gcmVzdWx0O1xufVxuXG5mdW5jdGlvbiBuZXdTaHVmZmxlKGFycmF5LCBybmcgPSBNYXRoLnJhbmRvbSkge1xuICBjb25zdCByZXN1bHQgPSBhcnJheS5zbGljZSgpOyAvLyBDcmVhdGUgYSBjb3B5IG9mIHRoZSBhcnJheSB0byBhdm9pZCBtb2RpZnlpbmcgdGhlIG9yaWdpbmFsXG4gIGZvciAobGV0IGkgPSByZXN1bHQubGVuZ3RoIC0gMTsgaSA-IDA7IGktLSkge1xuICAgIGNvbnN0IGogPSBNYXRoLmZsb29yKHJuZygpICogKGkgKyAxKSk7IC8vIEdlbmVyYXRlIHJhbmRvbSBpbmRleCBmcm9tIDAgdG8gaSBpbmNsdXNpdmVcbiAgICBbcmVzdWx0W2ldLCByZXN1bHRbal1dID0gW3Jlc3VsdFtqXSwgcmVzdWx0W2ldXTsgLy8gU3dhcCBlbGVtZW50cyBlZmZpY2llbnRseVxuICB9XG4gIHJldHVybiByZXN1bHQ7XG59XG5cbmNvbnN0IFRFTl9NSUxMSU9OID0gMTAwMFxuY29uc3QgYXJyID0gQXJyYXkuZnJvbSh7bGVuZ3RoOiBURU5fTUlMTElPTn0pLm1hcCgoXywgaSkgPT4gaSlcblxucmV0dXJuIHtcbiAgbmV3U2h1ZmZsZSxcbiAgb2xkU2h1ZmZsZSxcbiAgYXJyXG59OyJ9fQ)

**Comment by dcousens** [comment]
Using your exact link, the average run time for the new code is slower than the existing code.

> Average run time: 0.0079 ms for "Old Shuffle"

> Average run time: 0.018 ms for "New Shuffle"

I think the results are probably highly variable, dependent on our browser versions and many other factors.

**Comment by vipansh** [comment]
@dcousens 
I still believe the `New Shuffle` is fast in theory, and I have demonstrated this practically. You may choose to approve or close it.

image

**Comment by dcousens** [comment]
Understood @vipansh, thanks for the contribution :yellow_heart:, but I think I'll pass on this for now

**Pull request closed without merging**
